### ISSUE TITLE
Correct the "Sent" HTTP_STATUS_CODE to 201 in the Documentation

### ISSUE THREAD

**Issue by KevinLeeMiguel** [pindoio/pindo-cli#29]
Hello,

In your documentation, you specify that when the SMS is sent successfully we get a **200 status code**, but what we really get is a **201 status code**

**Comment by kenessajr** [comment]
Issue fixed.

**Comment by KevinLeeMiguel** [comment]
Thanks for fixing the issue @kenessajr , your sms are very fast⚡⚡👌.
