### ISSUE TITLE
Organization command not documented enough

### ISSUE THREAD

**Issue by silverhairs** [pindoio/pindo-cli#40]
All the commands are self-explanatory, except `organization`. It's tricky to know what it does? edit an existing organization? migrate a normal user account to an organization??? would be helpful to add more comments in the [http.py](https://github.com/pindoio/pindo-cli/blob/master/pindo_cli/http.py) file

**Comment by kenessajr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pindo-cli upgrade](https://trello.com/c/X0IgxACZ/111-pindo-cli-upgrade)

**Comment by silverhairs** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Pindo-cli upgrade](https://trello.com/c/X0IgxACZ/111-pindo-cli-upgrade)

Awesome

**Comment by silverhairs** [comment]
awaiting the merge
