### ISSUE TITLE
ERR_FR_TOO_MANY_REDIRECTS When sending a  message

### ISSUE THREAD

**Issue by regisrex** [pindoio/pindo-cli#55]
I was trying to send a message by hitting `POST https://api.pindo.io/v1/sms`, but the message was't sent.  Looks like there're too much redirects happening there.

<img width="1288" alt="Screenshot 2024-09-20 at 2 01 44 PM" src="https://github.com/user-attachments/assets/8f038f50-9919-494a-ab0b-8aa05aa34529">

**Comment by Frankkwizera** [comment]
Could you share more details on the request payload, headers, and method used @regisrex

**Comment by regisrex** [comment]
Here
<img width="765" alt="image" src="https://github.com/user-attachments/assets/6f453b3d-c3cc-40f1-a3b6-847b1714067b">
And the body was something like this.
```json
{
    "to": "0780000000",
    "text": "Hola!",
    "sender": "regisrex"
}

```

**Comment by Rukamakama** [comment]
@regisrex Please add the trailing `/` to the request url or copy this `https://api.pindo.io/v1/sms/`

**Comment by regisrex** [comment]
it works, thanks @Rukamakama. Btw, how long does it take for the SMS to be delivered, minimum ?

**Comment by Rukamakama** [comment]
> it works, thanks @Rukamakama. Btw, how long does it take for the SMS to be delivered, minimum ?

The sms take 1 to 3 seconds to be delivered. Just make sure you are using an approved sender, if you don't have an approved one you can use `PindoTest` as sender.
